/**
 * Script: populate-master-input-sheet.ts
 * Description: Populates the Master Input Sheet with 100+ exhaustive UI & Backend test cases
 * Target Sheet: https://docs.google.com/spreadsheets/d/1KWWMQN3ppFfux1mP8Wb34UmtrIEXhz2T6_1_goXI8JI/edit
 */

import { google } from 'googleapis';
import * as path from 'path';

const SPREADSHEET_ID = '1KWWMQN3ppFfux1mP8Wb34UmtrIEXhz2T6_1_goXI8JI';
const KEY_FILE_PATH = path.resolve(__dirname, '../Google_service_account.json');

interface TestCase {
  id: string;
  module: string;
  suite: 'UI' | 'Backend API' | 'End-to-End';
  scenarioType: 'Positive' | 'Negative' | 'Edge Case' | 'Security' | 'Boundary' | 'Stress';
  title: string;
  description: string;
  preconditions: string;
  steps: string;
  testData: string;
  expectedResult: string;
  expectedStatus: string;
  priority: 'P0' | 'P1' | 'P2';
  automated: 'Automated';
}

const HEADERS = [
  'Test Case ID',
  'Module / Category',
  'Suite Type',
  'Scenario Type',
  'Test Title',
  'Description / Objective',
  'Preconditions',
  'Test Steps',
  'Test Data / Input Parameters',
  'Expected Result',
  'Expected Status Code / UI State',
  'Priority',
  'Automation Status',
];

const TEST_CASES: TestCase[] = [
  // ── 1. Authentication & Session Management ──────────────────────────────
  {
    id: 'TC-AUTH-001',
    module: 'Authentication & Session',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'New User Sign-Up with Valid Email & OTP',
    description: 'Verify a new user can register and receive email verification/OTP code',
    preconditions: 'User is on the login/signup modal; email is not previously registered',
    steps: '1. Enter new user email\n2. Click Continue/Sign Up\n3. Enter OTP received in inbox\n4. Submit OTP',
    testData: JSON.stringify({ email: 'newuser_test_qa@shunyalabs.ai', otp: '123456' }),
    expectedResult: 'User account created successfully, redirected to onboarding or playground with welcome state',
    expectedStatus: 'HTTP 200 / UI Redirect',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-AUTH-002',
    module: 'Authentication & Session',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Existing User Login with Valid Email & OTP/Password',
    description: 'Verify existing user (yamini@shunyalabs.ai) can log into the Playground successfully',
    preconditions: 'User has registered account; valid session credentials available',
    steps: '1. Navigate to Playground URL\n2. Click Login\n3. Enter email yamini@shunyalabs.ai\n4. Submit OTP/credentials',
    testData: JSON.stringify({ email: 'yamini@shunyalabs.ai' }),
    expectedResult: 'User logged in successfully; profile displays "Yamini Singh", credits balance visible',
    expectedStatus: 'HTTP 200 / Logged In State',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-AUTH-003',
    module: 'Authentication & Session',
    suite: 'UI',
    scenarioType: 'Negative',
    title: 'Login with Invalid / Expired OTP',
    description: 'Verify login fails when an incorrect or expired OTP is supplied',
    preconditions: 'User requested OTP on login modal',
    steps: '1. Enter valid email\n2. Request OTP\n3. Enter invalid OTP 000000\n4. Click Verify',
    testData: JSON.stringify({ email: 'yamini@shunyalabs.ai', otp: '000000' }),
    expectedResult: 'Error message "Invalid or expired OTP" displayed; user remains on login modal',
    expectedStatus: 'HTTP 400 / Error Toast',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-AUTH-004',
    module: 'Authentication & Session',
    suite: 'UI',
    scenarioType: 'Negative',
    title: 'Login with Empty Email Field',
    description: 'Verify form validation prevents submission when email field is blank',
    preconditions: 'Login modal is open',
    steps: '1. Leave email input empty\n2. Click Continue/Login button',
    testData: JSON.stringify({ email: '' }),
    expectedResult: 'Validation error "Please enter an email address" displayed; button disabled or submission blocked',
    expectedStatus: 'Client Validation Error',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-AUTH-005',
    module: 'Authentication & Session',
    suite: 'UI',
    scenarioType: 'Negative',
    title: 'Login with Malformed Email Format',
    description: 'Verify validation handles invalid email syntax (missing @, missing domain)',
    preconditions: 'Login modal is open',
    steps: '1. Enter "invalid-email-address"\n2. Click Continue\n3. Enter "user@domain"\n4. Click Continue',
    testData: JSON.stringify({ invalidEmails: ['invalid-email', 'user@', '@shunya.ai', 'user name@shunya.ai'] }),
    expectedResult: 'Field level error "Please enter a valid email address" appears',
    expectedStatus: 'Client Validation Error',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-AUTH-006',
    module: 'Authentication & Session',
    suite: 'UI',
    scenarioType: 'Security',
    title: 'Login Field SQL / Script Injection Resilience',
    description: 'Verify email input sanitizes potential XSS and SQL injection payloads',
    preconditions: 'Login modal is open',
    steps: '1. Enter "<script>alert(1)</script>"\n2. Enter "\' OR 1=1 --"\n3. Submit',
    testData: JSON.stringify({ payload: '\' OR 1=1 --<script>alert(1)</script>' }),
    expectedResult: 'Input rejected with invalid email error; no script execution or server crash',
    expectedStatus: 'HTTP 400 / Validation Error',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-AUTH-007',
    module: 'Authentication & Session',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'User Logout from Profile Menu',
    description: 'Verify logged-in user can log out and session tokens are cleared',
    preconditions: 'User is logged in',
    steps: '1. Click User Profile button ("Yamini Singh")\n2. Click "Log out" option\n3. Verify page redirects to unauthenticated state',
    testData: JSON.stringify({ user: 'Yamini Singh' }),
    expectedResult: 'User logged out, auth tokens removed from cookies/storageState, Login CTA visible',
    expectedStatus: 'HTTP 200 / Unauthenticated State',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-AUTH-008',
    module: 'Authentication & Session',
    suite: 'UI',
    scenarioType: 'Edge Case',
    title: 'Session Persistence Across Page Reloads',
    description: 'Verify user remains authenticated when reloading Playground browser page',
    preconditions: 'User is authenticated',
    steps: '1. Navigate to Playground\n2. Verify user logged in\n3. Reload page via F5/browser reload\n4. Verify user state',
    testData: JSON.stringify({ storageState: 'auth/playground-auth.json' }),
    expectedResult: 'User remains logged in; profile name and credits balance immediately visible',
    expectedStatus: 'HTTP 200 / Authenticated',
    priority: 'P1',
    automated: 'Automated',
  },

  // ── 2. Onboarding Journey ────────────────────────────────────────────────
  {
    id: 'TC-ONBOARD-001',
    module: 'Onboarding Journey',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'New User Onboarding Banner Display ($5 Credits Offer)',
    description: 'Verify new user sees onboarding banner offering $5 in free testing credits',
    preconditions: 'New user logged in without completed onboarding profile',
    steps: '1. Navigate to Playground\n2. Inspect top banner area for "$5 in credits" onboarding prompt',
    testData: JSON.stringify({ bannerKeyword: 'receive $5 in credits' }),
    expectedResult: 'Banner "Complete your onboarding to receive $5 in credits" is visible with CTA',
    expectedStatus: 'UI Rendered',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-ONBOARD-002',
    module: 'Onboarding Journey',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Complete Onboarding Journey Flow',
    description: 'Verify clicking onboarding CTA, filling required survey/company details, and receiving $5 credits',
    preconditions: 'New user on Playground with onboarding banner visible',
    steps: '1. Click "Complete Now" on onboarding banner\n2. Select role, company size, use case in modal\n3. Click Submit\n4. Verify credits updated to $5.00',
    testData: JSON.stringify({ role: 'QA Engineer', company: 'Shunya Labs', useCase: 'Speech to Text' }),
    expectedResult: 'Onboarding completed toast displayed; credits balance increments by $5.00; banner disappears',
    expectedStatus: 'HTTP 200 / Balance Updated ($5.00)',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-ONBOARD-003',
    module: 'Onboarding Journey',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Dismiss / Skip Onboarding Banner',
    description: 'Verify user can dismiss the onboarding banner and continue using the playground with initial balance',
    preconditions: 'User sees onboarding banner',
    steps: '1. Click close/dismiss icon (X) on onboarding banner\n2. Verify banner is removed from view\n3. Verify playground tools remain usable',
    testData: JSON.stringify({ action: 'dismiss' }),
    expectedResult: 'Banner closes smoothly; page layout adjusts without overlap',
    expectedStatus: 'UI Updated',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-ONBOARD-004',
    module: 'Onboarding Journey',
    suite: 'UI',
    scenarioType: 'Edge Case',
    title: 'Attempt Run Analysis with $0 Balance Prior to Onboarding',
    description: 'Verify attempting analysis with 0 credits triggers onboarding completion modal / Add Funds CTA',
    preconditions: 'User has $0.00 credits balance',
    steps: '1. Upload audio file\n2. Click Run Analysis button\n3. Observe modal/CTA response',
    testData: JSON.stringify({ credits: 0, file: 'test-audio.wav' }),
    expectedResult: 'Modal appears prompting user to complete onboarding for $5 credits or add billing funds',
    expectedStatus: 'UI Modal / Action Blocked',
    priority: 'P1',
    automated: 'Automated',
  },

  // ── 3. UI — Layout, Navigation & Branding ────────────────────────────────
  {
    id: 'TC-UI-LAY-001',
    module: 'UI - Layout & Navigation',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Playground Page Branding & Header Titles',
    description: 'Verify header title "API Playground" and subtitle description render cleanly',
    preconditions: 'Playground page loaded',
    steps: '1. Navigate to https://playground.shunyalabs.ai\n2. Assert page title contains "Playground"\n3. Assert heading "API Playground" is visible',
    testData: JSON.stringify({ url: 'https://playground.shunyalabs.ai' }),
    expectedResult: 'Header branding, Shunya Labs logo, Docs, Console, and User buttons visible',
    expectedStatus: 'HTTP 200 / DOM Rendered',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-LAY-002',
    module: 'UI - Layout & Navigation',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Service Tabs Switching (Speech to Text <-> Text to Speech)',
    description: 'Verify switching between STT and TTS tabs updates the active workspace panel',
    preconditions: 'Playground page loaded',
    steps: '1. Click "Text to Speech" tab\n2. Verify TTS workspace renders (Voice, Text input)\n3. Click "Speech to Text" tab\n4. Verify STT workspace renders (Model, Upload audio)',
    testData: JSON.stringify({ tabs: ['Speech to Text', 'Text to Speech'] }),
    expectedResult: 'Workspace toggles smoothly; no leftover artifacts or unresponsive buttons',
    expectedStatus: 'UI Tab Switch OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-LAY-003',
    module: 'UI - Layout & Navigation',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Credits Balance Display & Currency Formatting',
    description: 'Verify credits display shows valid dollar amount (e.g. Credits: $10.00)',
    preconditions: 'User authenticated',
    steps: '1. Locate Credits badge in Configuration header\n2. Validate regex match for `Credits:\\s*\\$[\\d,.-]+`',
    testData: JSON.stringify({ regex: 'Credits:\\s*\\$[\\d,.-]+' }),
    expectedResult: 'Credits amount is numeric and accurately reflects user wallet balance',
    expectedStatus: 'UI Badge Rendered',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-LAY-004',
    module: 'UI - Layout & Navigation',
    suite: 'UI',
    scenarioType: 'Edge Case',
    title: 'Responsive Viewport Resilience (Desktop, Tablet, Mobile)',
    description: 'Verify layout adjusts gracefully across 1920x1080, 768x1024, and 375x812 screens',
    preconditions: 'Browser viewport dynamic resizing',
    steps: '1. Load page at 1920x1080 (Desktop)\n2. Resize to 768x1024 (Tablet)\n3. Resize to 375x812 (Mobile)\n4. Check element visibility',
    testData: JSON.stringify({ viewports: [{ w: 1920, h: 1080 }, { w: 768, h: 1024 }, { w: 375, h: 812 }] }),
    expectedResult: 'No horizontal overflow or overlapping text; configuration and upload cards stack vertically on mobile',
    expectedStatus: 'Responsive Layout OK',
    priority: 'P2',
    automated: 'Automated',
  },

  // ── 4. UI — STT Models & Language Configuration ──────────────────────────
  {
    id: 'TC-UI-MOD-001',
    module: 'UI - Model & Language Selection',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Model Dropdown Contains All Model Families',
    description: 'Verify Model dropdown includes Zero Indic, Zero Codeswitch, and Zero Med',
    preconditions: 'STT tab active',
    steps: '1. Locate Model dropdown select element\n2. Verify option list contains "Zero Indic", "Zero Codeswitch", "Zero Med"',
    testData: JSON.stringify({ expectedModels: ['Zero Indic', 'Zero Codeswitch', 'Zero Med'] }),
    expectedResult: 'All 3 models present and selectable',
    expectedStatus: 'UI Select Options OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-MOD-002',
    module: 'UI - Model & Language Selection',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Switching Models Updates Transcription Engine Selection',
    description: 'Verify selecting Zero Codeswitch updates dropdown value to "Zero Codeswitch"',
    preconditions: 'STT tab active',
    steps: '1. Select "Zero Codeswitch"\n2. Assert select.inputValue() is "Zero Codeswitch"\n3. Switch to "Zero Indic"\n4. Assert select.inputValue() is "Zero Indic"',
    testData: JSON.stringify({ models: ['Zero Codeswitch', 'Zero Indic'] }),
    expectedResult: 'Active model updates correctly without error',
    expectedStatus: 'UI Value Updated',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-LANG-001',
    module: 'UI - Model & Language Selection',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Language Selector Modal & Indic Language Search (Hindi)',
    description: 'Verify clicking Language opens search modal and typing "Hindi" selects Hindi',
    preconditions: 'STT tab active',
    steps: '1. Click Language selector button\n2. Type "Hindi" in "Search languages..." input\n3. Click Hindi in results list\n4. Verify button label displays Hindi flag & name',
    testData: JSON.stringify({ search: 'Hindi', expectedLang: '🇮🇳 Hindi हिन्दी' }),
    expectedResult: 'Language updated to Hindi; modal closes cleanly',
    expectedStatus: 'UI Language Selected',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-LANG-002',
    module: 'UI - Model & Language Selection',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Language Selection Across South Indic Languages (Telugu, Tamil, Kannada, Malayalam)',
    description: 'Verify regional Dravidian languages can be searched and selected',
    preconditions: 'STT tab active',
    steps: '1. Click Language selector\n2. Search "Telugu" and select\n3. Repeat for "Tamil", "Kannada", "Malayalam"',
    testData: JSON.stringify({ languages: ['Telugu', 'Tamil', 'Kannada', 'Malayalam'] }),
    expectedResult: 'Each language item is found in the list and updates the selection',
    expectedStatus: 'UI Language Selected',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-LANG-003',
    module: 'UI - Model & Language Selection',
    suite: 'UI',
    scenarioType: 'Negative',
    title: 'Language Search with Non-Existent Query',
    description: 'Verify searching with a bogus keyword (e.g. "XYZ999") shows "No languages found"',
    preconditions: 'Language search modal open',
    steps: '1. Open language search\n2. Type "XYZ999_NON_EXISTENT"\n3. Check list state',
    testData: JSON.stringify({ query: 'XYZ999_NON_EXISTENT' }),
    expectedResult: 'List is empty or displays "No languages found"; no crash',
    expectedStatus: 'UI Empty State',
    priority: 'P2',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-LANG-004',
    module: 'UI - Model & Language Selection',
    suite: 'UI',
    scenarioType: 'Edge Case',
    title: 'Language Search with Special Characters',
    description: 'Verify searching with symbols like `!@#$%^&*()` handles input gracefully without crashing',
    preconditions: 'Language search modal open',
    steps: '1. Open language search\n2. Type "!@#$%^&*()"\n3. Observe UI response',
    testData: JSON.stringify({ query: '!@#$%^&*()' }),
    expectedResult: 'Input handled safely; no regex crash or unhandled UI exception',
    expectedStatus: 'UI Safe Empty State',
    priority: 'P2',
    automated: 'Automated',
  },

  // ── 5. UI — Audio Upload & Player Controls ────────────────────────────────
  {
    id: 'TC-UI-UPL-001',
    module: 'UI - Audio Upload & Player',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Upload Valid WAV Audio File',
    description: 'Verify uploading a standard 16kHz WAV audio file enables Run Analysis button',
    preconditions: 'STT tab active; sample WAV file available',
    steps: '1. Set input files on hidden file input with "test-audio.wav"\n2. Wait for upload card to populate\n3. Verify "Run Analysis" button becomes enabled',
    testData: JSON.stringify({ file: 'src/fixtures/sample-hindi.wav', format: 'audio/wav' }),
    expectedResult: 'File uploaded successfully; audio player appears; Run Analysis enabled',
    expectedStatus: 'UI Player Active / Button Enabled',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-UPL-002',
    module: 'UI - Audio Upload & Player',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Upload Valid MP3 Audio File',
    description: 'Verify uploading an MP3 audio file is recognized and player controls appear',
    preconditions: 'STT tab active; sample MP3 file available',
    steps: '1. Set input files with "test-audio.mp3"\n2. Verify waveform / audio duration is rendered\n3. Verify Run Analysis button is enabled',
    testData: JSON.stringify({ file: 'src/fixtures/sample-audio.mp3', format: 'audio/mpeg' }),
    expectedResult: 'MP3 file uploaded; Run Analysis button is clickable',
    expectedStatus: 'UI Button Enabled',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-UPL-003',
    module: 'UI - Audio Upload & Player',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Remove Uploaded Audio File',
    description: 'Verify clicking Remove / Trash icon resets the upload area to dropzone',
    preconditions: 'Audio file currently uploaded in player',
    steps: '1. Upload audio file\n2. Click Remove / Delete button\n3. Verify upload dropzone "Choose Audio File" is restored\n4. Verify Run Analysis is disabled/reset',
    testData: JSON.stringify({ action: 'remove_uploaded_audio' }),
    expectedResult: 'Audio removed; player dismissed; upload dropzone restored',
    expectedStatus: 'UI State Reset',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-UPL-004',
    module: 'UI - Audio Upload & Player',
    suite: 'UI',
    scenarioType: 'Negative',
    title: 'Upload Invalid File Format (.txt / .pdf)',
    description: 'Verify attempting to upload a non-audio file is rejected gracefully',
    preconditions: 'STT tab active',
    steps: '1. Attempt to upload "test-invalid.txt"\n2. Observe rejection message or lack of player activation',
    testData: JSON.stringify({ file: 'test-invalid.txt', content: 'Not an audio file' }),
    expectedResult: 'Error toast or rejection handled; Run Analysis remains disabled or displays invalid file format error',
    expectedStatus: 'UI Format Rejection',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-UPL-005',
    module: 'UI - Audio Upload & Player',
    suite: 'UI',
    scenarioType: 'Boundary',
    title: 'Upload 0-Byte Empty Audio File',
    description: 'Verify 0-byte file upload does not crash the UI or frontend player',
    preconditions: 'STT tab active',
    steps: '1. Create 0-byte file "empty.wav"\n2. Upload to playground\n3. Verify error handling',
    testData: JSON.stringify({ file: 'empty.wav', size: 0 }),
    expectedResult: 'UI rejects or server responds with error without freezing browser tab',
    expectedStatus: 'HTTP 400 / Client Error',
    priority: 'P1',
    automated: 'Automated',
  },

  // ── 6. UI — All 12 Audio Intelligence Features ───────────────────────────
  {
    id: 'TC-UI-FEAT-001',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 1: Translation (English / Hindi Target)',
    description: 'Verify enabling Translation opens language target modal and activates feature row',
    preconditions: 'STT tab active; Features sub-tab open',
    steps: '1. Click "Translation" feature row\n2. Select Hindi target in modal\n3. Click Confirm\n4. Verify row displays active state',
    testData: JSON.stringify({ feature: 'Translation', targetLang: 'hi' }),
    expectedResult: 'Translation feature active in UI; multipart request receives translation params',
    expectedStatus: 'UI Feature Active',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-002',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 2: Transliteration (Devanagari / Latin)',
    description: 'Verify enabling Transliteration opens script selector and confirms selection',
    preconditions: 'STT tab active',
    steps: '1. Click "Transliteration" row\n2. Select Devanagari script\n3. Click Confirm',
    testData: JSON.stringify({ feature: 'Transliteration', script: 'Devanagari' }),
    expectedResult: 'Transliteration activated',
    expectedStatus: 'UI Feature Active',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-003',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 3: Speaker Diarization',
    description: 'Verify enabling Speaker Diarization toggles segment speaker tagging',
    preconditions: 'STT tab active',
    steps: '1. Click "Speaker Diarization" row\n2. Verify toggle activation',
    testData: JSON.stringify({ feature: 'Speaker Diarization' }),
    expectedResult: 'Speaker Diarization active; output will segment by Speaker 0, Speaker 1',
    expectedStatus: 'UI Feature Active',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-004',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 4: Speaker Identification',
    description: 'Verify enabling Speaker Identification activates voice profile matching',
    preconditions: 'STT tab active',
    steps: '1. Click "Speaker Identification" row\n2. Verify toggle state',
    testData: JSON.stringify({ feature: 'Speaker Identification' }),
    expectedResult: 'Speaker Identification active',
    expectedStatus: 'UI Feature Active',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-005',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 5: Word Timestamps',
    description: 'Verify enabling Word Timestamps requests word-level start/end offsets',
    preconditions: 'STT tab active',
    steps: '1. Click "Word Timestamps" row\n2. Verify toggle state',
    testData: JSON.stringify({ feature: 'Word Timestamps' }),
    expectedResult: 'Word Timestamps active; JSON payload will include words array',
    expectedStatus: 'UI Feature Active',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-006',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 6: Profanity Hashing',
    description: 'Verify enabling Profanity Hashing masks sensitive words with asterisks',
    preconditions: 'STT tab active',
    steps: '1. Click "Profanity Hashing" row\n2. Verify toggle state',
    testData: JSON.stringify({ feature: 'Profanity Hashing' }),
    expectedResult: 'Profanity Hashing active',
    expectedStatus: 'UI Feature Active',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-007',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 7: Custom Keyword Hashing',
    description: 'Verify entering comma-separated keywords into Custom Keyword Hashing modal',
    preconditions: 'STT tab active',
    steps: '1. Click "Custom Keyword Hashing"\n2. Type "shunya,testing" into modal input\n3. Click Confirm',
    testData: JSON.stringify({ feature: 'Custom Keyword Hashing', keywords: 'shunya,testing' }),
    expectedResult: 'Keywords saved and feature activated',
    expectedStatus: 'UI Feature Active',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-008',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 8: Intent Detection',
    description: 'Verify enabling Intent Detection opens intent taxonomy modal and confirms intent classes',
    preconditions: 'STT tab active',
    steps: '1. Click "Intent Detection"\n2. Select intent choices (e.g. refund, order, complaint)\n3. Click Confirm',
    testData: JSON.stringify({ feature: 'Intent Detection', choices: 'refund,order,support' }),
    expectedResult: 'Intent Detection active',
    expectedStatus: 'UI Feature Active',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-009',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 9: Sentiment Analysis',
    description: 'Verify enabling Sentiment Analysis classifies audio sentiment (Positive/Negative/Neutral)',
    preconditions: 'STT tab active',
    steps: '1. Click "Sentiment Analysis" row\n2. Verify toggle state',
    testData: JSON.stringify({ feature: 'Sentiment Analysis' }),
    expectedResult: 'Sentiment Analysis active',
    expectedStatus: 'UI Feature Active',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-010',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 10: Emotion Diarization',
    description: 'Verify enabling Emotion Diarization tags emotion states per audio segment',
    preconditions: 'STT tab active',
    steps: '1. Click "Emotion Diarization" row\n2. Verify toggle state',
    testData: JSON.stringify({ feature: 'Emotion Diarization' }),
    expectedResult: 'Emotion Diarization active',
    expectedStatus: 'UI Feature Active',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-011',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 11: Summarisation',
    description: 'Verify enabling Summarisation requests executive abstract of the conversation',
    preconditions: 'STT tab active',
    steps: '1. Click "Summarisation" row\n2. Verify toggle state',
    testData: JSON.stringify({ feature: 'Summarisation', max_length: 150 }),
    expectedResult: 'Summarisation active',
    expectedStatus: 'UI Feature Active',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-012',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Toggle Feature 12: Keyword Normalisation',
    description: 'Verify entering keyterms in Keyword Normalisation modal formats domain entities',
    preconditions: 'STT tab active',
    steps: '1. Click "Keyword Normalisation"\n2. Enter "order,invoice"\n3. Click Confirm',
    testData: JSON.stringify({ feature: 'Keyword Normalisation', terms: 'order,invoice' }),
    expectedResult: 'Keyword Normalisation active',
    expectedStatus: 'UI Feature Active',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-FEAT-013',
    module: 'UI - Intelligence Features',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Multi-Feature Matrix Combination (Timestamps + Diarization + Sentiment + Intent)',
    description: 'Verify enabling 4 features simultaneously creates valid multi-feature request payload',
    preconditions: 'STT tab active; audio uploaded',
    steps: '1. Enable Word Timestamps\n2. Enable Speaker Diarization\n3. Enable Sentiment Analysis\n4. Enable Intent Detection\n5. Upload audio\n6. Click Run Analysis',
    testData: JSON.stringify({ features: ['Word Timestamps', 'Speaker Diarization', 'Sentiment Analysis', 'Intent Detection'] }),
    expectedResult: 'Analysis executes; all 4 intelligence features rendered in transcript/JSON views',
    expectedStatus: 'HTTP 200 / Full Intelligence Output',
    priority: 'P0',
    automated: 'Automated',
  },

  // ── 7. UI — Output Displays & Code Export ─────────────────────────────────
  {
    id: 'TC-UI-OUT-001',
    module: 'UI - Output & Code Export',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Output View: Transcript Tab vs JSON Tab Switching',
    description: 'Verify user can switch between readable transcript view and formatted JSON tree view',
    preconditions: 'Analysis completed with output rendered',
    steps: '1. Click "JSON" tab\n2. Verify JSON code block visible\n3. Click "Transcript" tab\n4. Verify text segments visible',
    testData: JSON.stringify({ tabs: ['Transcript', 'JSON'] }),
    expectedResult: 'Both output tabs render corresponding view smoothly',
    expectedStatus: 'UI Tab View OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-OUT-002',
    module: 'UI - Output & Code Export',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'Code Sample Tab: Python Code Snippet & Copy Action',
    description: 'Verify Code Sample tab renders `main.py` code snippet and Copy Code button is clickable',
    preconditions: 'STT workspace active',
    steps: '1. Click "Code Sample" tab\n2. Verify `main.py` snippet appears\n3. Click "Copy Code" button\n4. Verify button responds with copied state',
    testData: JSON.stringify({ file: 'main.py' }),
    expectedResult: 'Code sample displayed accurately reflecting selected configuration; copied to clipboard',
    expectedStatus: 'UI Code Sample OK',
    priority: 'P1',
    automated: 'Automated',
  },

  // ── 8. UI — Text to Speech (TTS) Synthesis ────────────────────────────────
  {
    id: 'TC-TTS-UI-001',
    module: 'UI - Text to Speech',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'TTS Input Area Accepts Multi-Language Text & Updates Character Counter',
    description: 'Verify entering Hindi/English text updates textarea value and length counter',
    preconditions: 'TTS tab active',
    steps: '1. Click "Text to Speech" tab\n2. Type "नमस्ते, शून्या लैब्स में आपका स्वागत है।"\n3. Verify text in textarea',
    testData: JSON.stringify({ text: 'नमस्ते, शून्या लैब्स में आपका स्वागत है।' }),
    expectedResult: 'Text input displays unicode Indic characters accurately',
    expectedStatus: 'UI Textarea Updated',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-TTS-UI-002',
    module: 'UI - Text to Speech',
    suite: 'UI',
    scenarioType: 'Positive',
    title: 'TTS Voice Dropdown Selection',
    description: 'Verify Voice selector displays available female and male voice profiles',
    preconditions: 'TTS tab active',
    steps: '1. Click Voice selector dropdown\n2. Verify voice options (shunya-female-1, shunya-male-1, etc.)\n3. Select a voice profile',
    testData: JSON.stringify({ voices: ['shunya-female-1', 'shunya-male-1'] }),
    expectedResult: 'Voice profile selected',
    expectedStatus: 'UI Voice Selected',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-TTS-UI-003',
    module: 'UI - Text to Speech',
    suite: 'UI',
    scenarioType: 'Negative',
    title: 'TTS Negative: Empty Text Submission Blocked',
    description: 'Verify clicking Generate Speech with blank text input is disabled or displays error',
    preconditions: 'TTS tab active; textarea empty',
    steps: '1. Clear textarea\n2. Observe "Generate Speech" button state or click\n3. Verify validation prompt',
    testData: JSON.stringify({ text: '' }),
    expectedResult: 'Button disabled or validation toast "Please enter text to synthesize" appears',
    expectedStatus: 'Client Validation Toast',
    priority: 'P1',
    automated: 'Automated',
  },

  // ── 9. UI — Negative & Edge Cases ─────────────────────────────────────────
  {
    id: 'TC-UI-EDGE-001',
    module: 'UI - Negative & Edge Cases',
    suite: 'UI',
    scenarioType: 'Stress',
    title: 'Rapid Service Tab Toggling Stress Test',
    description: 'Verify rapidly switching between STT and TTS tabs 10+ times does not crash frontend',
    preconditions: 'Playground loaded',
    steps: '1. Loop 10 times clicking STT then TTS tab\n2. Verify final page state remains interactive and healthy',
    testData: JSON.stringify({ iterations: 10 }),
    expectedResult: 'No JavaScript unhandled exceptions; UI stays responsive',
    expectedStatus: 'HTTP 200 / Stable UI',
    priority: 'P2',
    automated: 'Automated',
  },
  {
    id: 'TC-UI-EDGE-002',
    module: 'UI - Negative & Edge Cases',
    suite: 'UI',
    scenarioType: 'Edge Case',
    title: 'Zero Console Errors on Clean Load',
    description: 'Verify no critical JavaScript runtime errors logged in browser console',
    preconditions: 'Playground loaded',
    steps: '1. Attach page error listener\n2. Navigate to Playground with networkidle\n3. Assert 0 critical page errors',
    testData: JSON.stringify({ filter: 'exclude third-party analytics' }),
    expectedResult: '0 critical JavaScript console errors',
    expectedStatus: '0 Console Errors',
    priority: 'P1',
    automated: 'Automated',
  },

  // ── 10. Backend API — Health & Microservices ─────────────────────────────
  {
    id: 'TC-API-HLTH-001',
    module: 'Backend API - Health & Languages',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'GET ASR Production Health Endpoint (GET /health)',
    description: 'Verify ASR production V2 microservice responds with healthy status and latency < 2000ms',
    preconditions: 'ASR V2 service is live at https://asrv2prod.shunyalabs.ai',
    steps: '1. Send GET https://asrv2prod.shunyalabs.ai/health\n2. Measure latency\n3. Assert status code 200',
    testData: JSON.stringify({ endpoint: 'https://asrv2prod.shunyalabs.ai/health' }),
    expectedResult: 'HTTP 200 OK; status healthy; latency < 2000ms',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-HLTH-002',
    module: 'Backend API - Health & Languages',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'GET TTS Production Health Endpoint (GET /health)',
    description: 'Verify TTS production V2 microservice responds with healthy status and latency < 2000ms',
    preconditions: 'TTS V2 service is live at https://ttsv2.shunyalabs.ai',
    steps: '1. Send GET https://ttsv2.shunyalabs.ai/health\n2. Measure latency\n3. Assert status code 200',
    testData: JSON.stringify({ endpoint: 'https://ttsv2.shunyalabs.ai/health' }),
    expectedResult: 'HTTP 200 OK; latency < 2000ms',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-HLTH-003',
    module: 'Backend API - Health & Languages',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'GET Supported Languages Endpoint (GET /languages)',
    description: 'Verify language catalog returns complete list of 55+ supported Indic language codes',
    preconditions: 'ASR V2 service is live',
    steps: '1. Send GET https://asrv2prod.shunyalabs.ai/languages\n2. Parse JSON response\n3. Verify contains hi, en, bn, ta, te, mr, gu, kn, ml',
    testData: JSON.stringify({ endpoint: 'https://asrv2prod.shunyalabs.ai/languages' }),
    expectedResult: 'HTTP 200 OK; JSON contains supported language codes dictionary/array',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P1',
    automated: 'Automated',
  },

  // ── 11. Backend API — Direct ASR Model Matrix ────────────────────────────
  {
    id: 'TC-API-MOD-001',
    module: 'Backend API - ASR Model Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'POST /v1/audio/transcriptions — Model: zero-indic (WAV Audio)',
    description: 'Verify direct transcription using zero-indic model on standard WAV file',
    preconditions: 'Valid API Key / Bearer token available; sample WAV exists',
    steps: '1. POST multipart payload with file, model="zero-indic", language_code="auto"\n2. Assert status 200\n3. Assert response has "text" property with length > 0',
    testData: JSON.stringify({ model: 'zero-indic', language_code: 'auto', file: 'sample.wav' }),
    expectedResult: 'HTTP 200 OK; text transcript returned accurately',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-MOD-002',
    module: 'Backend API - ASR Model Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'POST /v1/audio/transcriptions — Model: zero-indic (MP3 Audio)',
    description: 'Verify direct transcription using zero-indic model on MP3 audio file',
    preconditions: 'Valid API Key; sample MP3 exists',
    steps: '1. POST multipart with file, model="zero-indic", language_code="auto"\n2. Assert status 200\n3. Assert body contains text',
    testData: JSON.stringify({ model: 'zero-indic', language_code: 'auto', file: 'sample.mp3' }),
    expectedResult: 'HTTP 200 OK; MP3 decoded and transcribed',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-MOD-003',
    module: 'Backend API - ASR Model Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'POST /v1/audio/transcriptions — Model: zero-codeswitch (Mixed Hinglish Audio)',
    description: 'Verify direct transcription on code-mixed Hindi-English audio using zero-codeswitch',
    preconditions: 'Valid API Key; Hinglish audio file',
    steps: '1. POST multipart with file, model="zero-codeswitch", language_code="auto"\n2. Assert status 200\n3. Assert text property is non-empty string',
    testData: JSON.stringify({ model: 'zero-codeswitch', language_code: 'auto', file: 'hinglish.wav' }),
    expectedResult: 'HTTP 200 OK; mixed language transcribed in Latin/Devanagari script',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-MOD-004',
    module: 'Backend API - ASR Model Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'POST /v1/audio/transcriptions — Model: zero-medasr (Medical Consultation Audio)',
    description: 'Verify direct transcription on clinical medical audio using zero-medasr model',
    preconditions: 'Valid API Key; medical consultation audio',
    steps: '1. POST multipart with file, model="zero-medasr", language_code="en"\n2. Assert status 200/201\n3. Assert text returned',
    testData: JSON.stringify({ model: 'zero-medasr', language_code: 'en', file: 'medical.mp3' }),
    expectedResult: 'HTTP 200/201 OK; medical terms transcribed accurately',
    expectedStatus: 'HTTP 200/201 OK',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-API-MOD-005',
    module: 'Backend API - ASR Model Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'POST /v1/audio/transcriptions — Explicit Language Code (Hindi: hi)',
    description: 'Verify specifying explicit language_code="hi" forces Hindi decoding',
    preconditions: 'Valid API Key; Hindi audio',
    steps: '1. POST multipart with file, model="zero-indic", language_code="hi"\n2. Assert status 200\n3. Assert body contains text',
    testData: JSON.stringify({ model: 'zero-indic', language_code: 'hi', file: 'sample.wav' }),
    expectedResult: 'HTTP 200 OK; transcription text returned in Hindi script',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },

  // ── 12. Backend API — Direct ASR Feature Matrix ──────────────────────────
  {
    id: 'TC-API-FEAT-001',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 1: Translation (English Target)',
    description: 'Verify `translation=true` and `target_languages=["en"]` returns translated English text',
    preconditions: 'Valid API Key; Indic audio',
    steps: '1. POST /v1/audio/transcriptions with translation="true", target_languages=["en"]\n2. Assert 200\n3. Verify body contains text',
    testData: JSON.stringify({ model: 'zero-codeswitch', translation: 'true', target_languages: '["en"]' }),
    expectedResult: 'HTTP 200 OK; translation output provided',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-002',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 2: Transliteration',
    description: 'Verify `transliteration=true` parameter returns script transliterated text',
    preconditions: 'Valid API Key; Hindi audio',
    steps: '1. POST with transliteration="true", language_code="hi"\n2. Assert 200\n3. Assert body contains text',
    testData: JSON.stringify({ model: 'zero-indic', language_code: 'hi', transliteration: 'true' }),
    expectedResult: 'HTTP 200 OK',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-003',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 3: Speaker Diarization',
    description: 'Verify `diarize=true` parameter generates multi-speaker segments',
    preconditions: 'Valid API Key; multi-speaker audio',
    steps: '1. POST with diarize="true"\n2. Assert 200\n3. Assert response body has speakers or segmented speaker labels',
    testData: JSON.stringify({ model: 'zero-indic', diarize: 'true' }),
    expectedResult: 'HTTP 200 OK; speaker diarization metadata returned',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-004',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 4: Word Timestamps',
    description: 'Verify `timestamps=true` returns word start and end offsets',
    preconditions: 'Valid API Key',
    steps: '1. POST with timestamps="true"\n2. Assert 200\n3. Assert body has segments with word timing info',
    testData: JSON.stringify({ model: 'zero-indic', timestamps: 'true' }),
    expectedResult: 'HTTP 200 OK; word timestamp offsets returned',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-005',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 5: Profanity Hashing',
    description: 'Verify `profanity=true` masks explicit words in transcription',
    preconditions: 'Valid API Key',
    steps: '1. POST with profanity="true"\n2. Assert 200\n3. Assert text returned',
    testData: JSON.stringify({ model: 'zero-indic', profanity: 'true' }),
    expectedResult: 'HTTP 200 OK',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-006',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 6: Custom Keyword Hashing',
    description: 'Verify `hash=true` and `keywords=["shunya", "testing"]` hashes custom keywords',
    preconditions: 'Valid API Key',
    steps: '1. POST with hash="true", keywords=["shunya", "testing"]\n2. Assert 200',
    testData: JSON.stringify({ model: 'zero-indic', hash: 'true', keywords: '["shunya", "testing"]' }),
    expectedResult: 'HTTP 200 OK',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-007',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 7: Intent Detection',
    description: 'Verify `intent=true` returns intent classification',
    preconditions: 'Valid API Key',
    steps: '1. POST with intent="true"\n2. Assert 200\n3. Assert body contains intent analysis',
    testData: JSON.stringify({ model: 'zero-indic', intent: 'true' }),
    expectedResult: 'HTTP 200 OK; intent analysis object returned',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-008',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 8: Sentiment Analysis',
    description: 'Verify `sentiment=true` returns sentiment analysis scores/labels',
    preconditions: 'Valid API Key',
    steps: '1. POST with sentiment="true"\n2. Assert 200\n3. Assert body contains sentiment info',
    testData: JSON.stringify({ model: 'zero-indic', sentiment: 'true' }),
    expectedResult: 'HTTP 200 OK; sentiment score returned',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-009',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 9: Emotion Diarization',
    description: 'Verify `emotion=true` returns emotion classifications per segment',
    preconditions: 'Valid API Key',
    steps: '1. POST with emotion="true"\n2. Assert 200',
    testData: JSON.stringify({ model: 'zero-indic', emotion: 'true' }),
    expectedResult: 'HTTP 200 OK; emotion data returned',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-010',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 10: Summarisation',
    description: 'Verify `summarize=true` generates executive summary of audio transcript',
    preconditions: 'Valid API Key',
    steps: '1. POST with summarize="true"\n2. Assert 200\n3. Assert summary field present in response',
    testData: JSON.stringify({ model: 'zero-indic', summarize: 'true' }),
    expectedResult: 'HTTP 200 OK; summary text returned',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-011',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 11: Keyword Normalisation',
    description: 'Verify `normalize=true` returns normalized text',
    preconditions: 'Valid API Key',
    steps: '1. POST with normalize="true"\n2. Assert 200',
    testData: JSON.stringify({ model: 'zero-indic', normalize: 'true' }),
    expectedResult: 'HTTP 200 OK',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-API-FEAT-012',
    module: 'Backend API - Intelligence Feature Matrix',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'API Feature 12: Combined Multi-Feature Payload (Timestamps + Diarization + Sentiment + Intent)',
    description: 'Verify combining 4 features in a single POST request returns complete rich payload',
    preconditions: 'Valid API Key; WAV audio',
    steps: '1. POST with timestamps="true", diarize="true", sentiment="true", intent="true"\n2. Assert status 200\n3. Verify all 4 sections in response',
    testData: JSON.stringify({ model: 'zero-indic', timestamps: 'true', diarize: 'true', sentiment: 'true', intent: 'true' }),
    expectedResult: 'HTTP 200 OK; combined payload includes text, timestamps, diarization, sentiment, intent',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },

  // ── 13. Backend API — Direct TTS Speech Synthesis ─────────────────────────
  {
    id: 'TC-API-TTS-001',
    module: 'Backend API - TTS Speech Synthesis',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'POST /v1/audio/speech — English Synthesis with Female Voice (MP3)',
    description: 'Verify synthesizing English text to MP3 audio buffer',
    preconditions: 'Valid API Key; TTS V2 endpoint active',
    steps: '1. POST https://ttsv2.shunyalabs.ai/v1/audio/speech with input="Hello from Shunya Labs", voice="shunya-female-1", response_format="mp3"\n2. Assert status 200\n3. Assert binary audio buffer returned',
    testData: JSON.stringify({ input: 'Hello from Shunya Labs', voice: 'shunya-female-1', response_format: 'mp3' }),
    expectedResult: 'HTTP 200 OK; Content-Type audio/mpeg with valid audio binary payload',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-TTS-002',
    module: 'Backend API - TTS Speech Synthesis',
    suite: 'Backend API',
    scenarioType: 'Positive',
    title: 'POST /v1/audio/speech — Hindi Synthesis with Speed Parameter (1.5x)',
    description: 'Verify synthesizing Hindi text with customized speed multiplier',
    preconditions: 'Valid API Key',
    steps: '1. POST with input="नमस्ते, यह शून्या लैब्स का परीक्षण है।", speed=1.5, voice="shunya-female-1"\n2. Assert 200',
    testData: JSON.stringify({ input: 'नमस्ते, यह शून्या लैब्स का परीक्षण है।', speed: 1.5, voice: 'shunya-female-1' }),
    expectedResult: 'HTTP 200 OK; Hindi speech generated at 1.5x speed',
    expectedStatus: 'HTTP 200 OK',
    priority: 'P0',
    automated: 'Automated',
  },

  // ── 14. Backend API — Negative, Auth & Stress Cases ───────────────────────
  {
    id: 'TC-API-NEG-001',
    module: 'Backend API - Negative, Auth & Stress',
    suite: 'Backend API',
    scenarioType: 'Negative',
    title: 'Missing Authorization Header Returns 401 Unauthorized',
    description: 'Verify ASR API enforces authentication by returning 401 when Authorization header is absent',
    preconditions: 'No auth headers sent',
    steps: '1. POST /v1/audio/transcriptions without Authorization header\n2. Assert response status code is 401',
    testData: JSON.stringify({ headers: {} }),
    expectedResult: 'HTTP 401 Unauthorized',
    expectedStatus: 'HTTP 401 Unauthorized',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-NEG-002',
    module: 'Backend API - Negative, Auth & Stress',
    suite: 'Backend API',
    scenarioType: 'Negative',
    title: 'Invalid API Key / Bearer Token Returns 401 or 403',
    description: 'Verify ASR API rejects malformed/forged API tokens',
    preconditions: 'Bad API key supplied',
    steps: '1. POST /v1/audio/transcriptions with Authorization: "Bearer invalid_key_xyz_123"\n2. Assert status is 401 or 403',
    testData: JSON.stringify({ Authorization: 'Bearer invalid_key_xyz_123' }),
    expectedResult: 'HTTP 401 / 403 Forbidden/Unauthorized',
    expectedStatus: 'HTTP 401 / 403',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-NEG-003',
    module: 'Backend API - Negative, Auth & Stress',
    suite: 'Backend API',
    scenarioType: 'Negative',
    title: 'Missing Audio File in Multipart Payload Returns 400 or 422',
    description: 'Verify ASR API returns validation error when file parameter is omitted from multipart form',
    preconditions: 'Valid API Key',
    steps: '1. POST multipart payload containing only model="zero-indic", language_code="hi" (no file)\n2. Assert status >= 400',
    testData: JSON.stringify({ model: 'zero-indic', language_code: 'hi' }),
    expectedResult: 'HTTP 400 Bad Request or HTTP 422 Unprocessable Entity',
    expectedStatus: 'HTTP 400 / 422',
    priority: 'P0',
    automated: 'Automated',
  },
  {
    id: 'TC-API-NEG-004',
    module: 'Backend API - Negative, Auth & Stress',
    suite: 'Backend API',
    scenarioType: 'Negative',
    title: 'Corrupted Audio Buffer Payload Returns 400 or 422',
    description: 'Verify sending random corrupt byte sequence as audio file is rejected with 400/422',
    preconditions: 'Valid API Key',
    steps: '1. Send corrupted byte buffer in file field\n2. Assert response status is >= 400',
    testData: JSON.stringify({ file: 'corrupted.wav', buffer: 'RIFF....WAVEfmt ....CORRUPTED_BYTES' }),
    expectedResult: 'HTTP 400 / 422 Client Error; server does not crash',
    expectedStatus: 'HTTP 400 / 422',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-API-NEG-005',
    module: 'Backend API - Negative, Auth & Stress',
    suite: 'Backend API',
    scenarioType: 'Boundary',
    title: '0-Byte Empty Audio File Payload Returns 400 or 422',
    description: 'Verify sending 0-byte buffer is rejected with 400/422',
    preconditions: 'Valid API Key',
    steps: '1. Send empty Buffer.alloc(0) as audio payload\n2. Assert status is >= 400',
    testData: JSON.stringify({ file: 'empty.wav', size: 0 }),
    expectedResult: 'HTTP 400 / 422 Client Error',
    expectedStatus: 'HTTP 400 / 422',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-API-NEG-006',
    module: 'Backend API - Negative, Auth & Stress',
    suite: 'Backend API',
    scenarioType: 'Negative',
    title: 'TTS API Missing Input Text Returns 400',
    description: 'Verify TTS endpoint returns 400 when input text field is missing or empty',
    preconditions: 'Valid API Key',
    steps: '1. POST https://ttsv2.shunyalabs.ai/v1/audio/speech with voice="shunya-female-1" (missing input)\n2. Assert status is 400',
    testData: JSON.stringify({ voice: 'shunya-female-1' }),
    expectedResult: 'HTTP 400 Bad Request',
    expectedStatus: 'HTTP 400 Bad Request',
    priority: 'P1',
    automated: 'Automated',
  },
  {
    id: 'TC-API-NEG-007',
    module: 'Backend API - Negative, Auth & Stress',
    suite: 'Backend API',
    scenarioType: 'Stress',
    title: 'Concurrency Stress Check (3 Parallel ASR Requests)',
    description: 'Verify ASR service handles burst of 3 simultaneous requests without dropping or crashing',
    preconditions: 'Valid API Key; sample WAV file',
    steps: '1. Dispatch 3 parallel POST /v1/audio/transcriptions requests via Promise.all\n2. Assert all requests return status 200 or 429 (rate-limited)',
    testData: JSON.stringify({ parallelRequests: 3, model: 'zero-indic' }),
    expectedResult: 'All 3 requests return HTTP 200 OK or 429; no 500 internal server errors',
    expectedStatus: 'HTTP 200 / 429 OK',
    priority: 'P1',
    automated: 'Automated',
  },
];

async function run() {
  console.log(`Connecting to Google Sheets API with service account key: ${KEY_FILE_PATH}`);
  const auth = new google.auth.GoogleAuth({
    keyFile: KEY_FILE_PATH,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });
  const sheets = google.sheets({ version: 'v4', auth });

  console.log(`Preparing ${TEST_CASES.length} test cases across UI and Backend suites...`);

  const rows: string[][] = [HEADERS];
  for (const tc of TEST_CASES) {
    rows.push([
      tc.id,
      tc.module,
      tc.suite,
      tc.scenarioType,
      tc.title,
      tc.description,
      tc.preconditions,
      tc.steps,
      tc.testData,
      tc.expectedResult,
      tc.expectedStatus,
      tc.priority,
      tc.automated,
    ]);
  }

  // 1. Clear existing sheet
  console.log(`Clearing existing content in Sheet1 of spreadsheet: ${SPREADSHEET_ID}`);
  await sheets.spreadsheets.values.clear({
    spreadsheetId: SPREADSHEET_ID,
    range: 'Sheet1!A1:Z500',
  });

  // 2. Write new rows
  console.log(`Writing ${rows.length} rows (header + ${TEST_CASES.length} test cases)...`);
  const updateRes = await sheets.spreadsheets.values.update({
    spreadsheetId: SPREADSHEET_ID,
    range: 'Sheet1!A1',
    valueInputOption: 'USER_ENTERED',
    requestBody: {
      values: rows,
    },
  });
  console.log(`Updated ${updateRes.data.updatedRows} rows, ${updateRes.data.updatedColumns} columns.`);

  // 3. Format header row (Dark Navy Blue background, white bold text, freeze top row)
  const meta = await sheets.spreadsheets.get({ spreadsheetId: SPREADSHEET_ID });
  const sheetId = meta.data.sheets?.[0]?.properties?.sheetId || 0;

  console.log(`Applying formatting to Sheet1 (ID: ${sheetId})...`);
  await sheets.spreadsheets.batchUpdate({
    spreadsheetId: SPREADSHEET_ID,
    requestBody: {
      requests: [
        // Freeze header row
        {
          updateSheetProperties: {
            properties: {
              sheetId,
              title: 'Master_Test_Scenarios',
              gridProperties: {
                frozenRowCount: 1,
              },
            },
            fields: 'title,gridProperties.frozenRowCount',
          },
        },
        // Header styling
        {
          repeatCell: {
            range: {
              sheetId,
              startRowIndex: 0,
              endRowIndex: 1,
              startColumnIndex: 0,
              endColumnIndex: HEADERS.length,
            },
            cell: {
              userEnteredFormat: {
                backgroundColor: { red: 0.08, green: 0.18, blue: 0.36 }, // Dark navy
                textFormat: {
                  foregroundColor: { red: 1, green: 1, blue: 1 },
                  bold: true,
                  fontSize: 11,
                },
                horizontalAlignment: 'CENTER',
                verticalAlignment: 'MIDDLE',
              },
            },
            fields: 'userEnteredFormat(backgroundColor,textFormat,horizontalAlignment,verticalAlignment)',
          },
        },
        // Auto-resize columns
        {
          autoResizeDimensions: {
            dimensions: {
              sheetId,
              dimension: 'COLUMNS',
              startIndex: 0,
              endIndex: HEADERS.length,
            },
          },
        },
      ],
    },
  });

  console.log('Master Input Sheet populated and formatted successfully!');
}

run().catch((err) => {
  console.error('Failed to populate master input sheet:', err);
  process.exit(1);
});
